### ISSUE TITLE
Badge Comments

### ISSUE THREAD

**Issue by jimbo8098** [GibbonEdu/module-badges#5]
Is there a way to see badge comments? If there is, I don't see one. Could potentially be added to the badges_view.php page as a clickable link, tooltip or simply text below:

![image](https://user-images.githubusercontent.com/12417556/57775843-e31f2b00-7715-11e9-92b8-04ed5859cb32.png)

**Comment by jimbo8098** [comment]
See that last PR for a suggestion :)

**Comment by rossdotparker** [comment]
Looks good Jim, thanks I'll close this now, and look at the PR later. Cheers : )
